services:
  web:
    build:
      context: .
      dockerfile: 'docker/api/Dockerfile'
    ports:
      - 8000:8000
  celery:
    build:
      context: .
      dockerfile: 'docker/celery/Dockerfile'
    depends_on:
      - redis
  flower:
    build:
      context: .
      dockerfile: 'docker/flower/Dockerfile'
    depends_on:
      - redis
    ports:
      - 5555:5555
  redis:
    image: redis
    ports:
      - "6379:6379"
